accounts/urls.py
from django.urls import path, include
from . import views
from smsgateaway import views as smsviews
urlpatterns = [
    path('', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('enter/', smsviews.sms_gateway_view, name='enter')
]

mhealth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from smsgateaway import views
from accounts import views as accviews
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('smsgateaway/', include('smsgateaway.urls')),
    path('', accviews.login, name='input'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
] 

smsgateaway/urls.py
from django.urls import path
from . import views

app_name = 'smsgateaway' 
urlpatterns = [
    path('input/', views.sms_gateway_view, name='input'),  
    path('result/', views.result_view, name='result'),
]

accounts/models.py
from django.db import models

# Create your models here.

smsgateaway/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class PhoneNumber(models.Model):
    number = models.CharField(max_length=15)

class Carrier(models.Model):
    name = models.CharField(max_length=255)
    phone_numbers = models.ManyToManyField(PhoneNumber)

    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth



def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2'] :
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error':'Username is already taken'})
            except User.DoesNotExist:
                user =  User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                auth.login(request, user)
                return redirect('enter')
        else:
            return render(request, 'accounts/signup.html', {'error':'Passwords don\'t match.'})
        
    else:
        #User want to enter the info
        return render(request, 'accounts/signup.html')

def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            auth.login(request, user)
            return redirect('enter')
        else:
            return render(request, 'accounts/login.html', {'error':'username or password is incorrect.'})       
    else:
        return render(request, 'accounts/login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('input')

smsgateaway/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from twilio.rest import Client as TwilioClient
import difflib
import os
from .models import PhoneNumber
import re
from dotenv import find_dotenv, load_dotenv

def input(request):
    numbers = PhoneNumber.objects
    return render(request, 'smsgateaway/base2.html', {'phonenumbers':numbers})

@login_required(login_url="/accounts/login")
def sms_gateway_view(request):
    if request.method == 'POST':
        raw_phone_number = request.POST.get('phone_number')
        phone_number = sanitize_phone_number(raw_phone_number)
        if not phone_number.isdigit():
            messages.error(request, 'Invalid phone number. Please enter a valid phone number.')
            return render(request, 'smsgateaway/input.html')
        carrier_name = look_up_carrier(phone_number)
        matching_carriers = match_carrier(carrier_name, phone_number)
        return render(request, 'smsgateaway/result.html', {'matching_carriers': matching_carriers})
    return render(request, 'smsgateaway/input.html')

def sanitize_phone_number(phone_number):
    phone_number = re.sub(r'\D', '', phone_number)
    if not phone_number or len(phone_number)<10:
        return ''
    return phone_number


def look_up_carrier(phone_number, country='US'):
    dotenv_path = find_dotenv()
    load_dotenv(dotenv_path)
    SID = os.getenv("SID")
    TOKEN = os.getenv("TOKEN")
    client = TwilioClient(SID, TOKEN)

    phone_data = client.lookups.v1.phone_numbers(phone_number).fetch(country_code=country, type=['carrier'])

    return phone_data.carrier['name']

def match_carrier(carrier, phone_number):
    carriers = get_clean_carrier_list(phone_number)

    close_matches = [c for c in carriers if carrier.split(" ")[0] in c]

    if len(close_matches) == 0:
        close_matches = difflib.get_close_matches(carrier, list(carriers))

    print(f"Closest matches to '{carrier}': {close_matches}")

    matching_carriers = {}

    for c in close_matches:
        matching_carriers[c] = carriers[c]

    return matching_carriers


def get_clean_carrier_list(phone_number):
    current_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_dir = os.path.join(current_path, 'data')
    carriers_file = os.path.join(data_dir, 'carriers.txt')

    with open(carriers_file, 'r') as f:
        lines = f.readlines()
        lines = [l.strip() for l in lines if len(l) > 2]

    carriers = {}

    for line in lines:
        if "@" not in line:
            carrier = line
            carriers[carrier] = []
        else:
            email= line.split("@")[1]
            format = phone_number + "@" + email
            carriers[carrier].append(format)

    return carriers


@login_required(login_url="/accounts/login")
def result_view(request):
    matching_carriers = request.GET.get('matching_carriers')
    return render(request, 'smsgateaway/result.html', {'matching_carriers': matching_carriers})

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block content %}

{%if error %}
{{error}}
<br/>
<br/>
{%endif%}

<h1>Login</h1>
<form method="POST" action="{%url 'login' %}">

    {% csrf_token %}
    Username:
    </br>
    <input type="text" name="username">
    </br>
    Password:
    </br>
    <input type="password" name="password">
    </br>
    </br>   
    <input class="btn btn-primary" type="submit" value="Login">

</form>

{%endblock%}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
  <p style="color: red; font-weight: bold; margin-bottom: 10px;">
    {{ error }}
  </p>
{% endif %}

<h1>Sign Up</h1>
<form method="POST" action="{% url 'signup' %}">

    {% csrf_token %}

    Username:
    <br>
    <input type="text" name="username">
    <br>
    Password:
    <br>
    <input type="password" name="password1">
    <br>
    Confirm Password:
    <br>
    <input type="password" name="password2">
    <br>
    <br>
    <input class="btn btn-primary" type="submit" value="Sign Up">

</form>

{% endblock %}

mhealth/templates/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">


  {% load static %}


  <head><script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>SMS LOOKUP</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    
  </head>
  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>



    
<header data-bs-theme="light" class="custom-header">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{%url 'input'%}"><ion-icon name="mail" class="base-icon"></ion-icon>
          SMS LOOKUP</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
                {%if user.is_authenticated%}
                <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout</a>
                <form id="logout" method="POST" action="{%url 'logout'%}">
                {% csrf_token %}
                <input type="hidden"/>
                </form>
                {%else %}
                <a class="nav-link" href="{%url 'signup'%}">Sign Up</a>
                <a class="nav-link" href="{%url 'login'%}">Login</a>
                <a class="nav-link" href="{%url 'password_reset'%}">Password Reset</a>
                {%endif%}
            </div>
          </div>
        </div>
      </nav>
</header>
<style>
  .navbar-brand {
    display: flex;
    align-items: center;
  }
  
  .base-icon {
    margin-right: 5px;
  }  
</style>

    <div class="container">
        {%block content%}
        {% endblock %}
    </div>




<footer class="text-body-secondary py-5">
  <div class="container text-center">
    <p>© IALS m-health  {%now "Y"%} </p>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    </body>
</html>

mhealth/templates/password_reset/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'login' %}">sign in</a> now.</p>
	</div>
</div>

{% endblock %}

mhealth/templates/password_reset/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

	<div class="d-flex flex-column">
		  <p class="m-auto p-2">
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p class="m-auto p-2">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'home' %}">Return to home page</a></p>
	</div>
</div>

{% endblock %}

mhealth/templates/password_reset/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Open-Chat Team
{% endautoescape %}

mhealth/templates/password_reset/password_reset_form.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>


<form id="id_password_reset_form" method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
    <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required="true" >
  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" >Send reset email</button>  
</form>



{% endblock %}

smsgateaway/templates/smsgateaway/input.html
{% extends 'base.html' %}

{% block content %}
<div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 50vh;">
  <form method="POST" action="{% url 'smsgateaway:input' %}">
    {% csrf_token %}
    <h1> <ion-icon name="send" class="small-icon"></ion-icon> Gateway</h1>
    <style>
    .small-icon {
      font-size: 25px; 
    }
  </style>
    <div>
      <label for="phone_number">Phone Number:</label>
      <br>
      <input type="text" name="phone_number" id="phone_number">
    </div>
    <br>
    <div style="display: flex; justify-content: center;">
      <input class="btn btn-primary" type="submit" value="Search">
    </div>
  </form>
  
  {% if messages %}
    <div class="messages" style="text-align: center; margin-top: 10px;">
      {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %} style="font-weight: bold; color: red;">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
</div>
{% endblock %}

smsgateaway/templates/smsgateaway/result.html
{% extends 'base.html' %}
{% block content %}
  <h1><ion-icon name="list-circle" class="small-icon"></ion-icon> Result</h1>
  <style>
    .small-icon {
      font-size: 25px; 
    }
  </style>
  {% if matching_carriers %}
    <ul>
    {% for carrier, addresses in matching_carriers.items %}
      <li>{{ carrier }}</li>
      <ul>
        {% for address in addresses %}
          <li>{{ address }}</li>
        {% endfor %}
      </ul>
    {% endfor %}
    </ul>
  {% else %}
    <p>No matching carriers found.</p>
  {% endif %}
{% endblock %}